# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods', :deterministic_uuids => false

target 'NEKaraoke' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NEKaraoke
  pod 'NEKaraokeUIKit', :path => '../NEKaraokeUIKit/NEKaraokeUIKit.podspec'
  pod 'NERtcSDK/RtcBasic','4.6.29'
  pod 'NERtcSDK/Beauty','4.6.29'
  pod 'NERtcSDK/FaceDetect','4.6.29'
  pod 'NERtcSDK/Segment','4.6.29'
  pod 'NIMSDK_LITE','9.6.4'

  pod 'YXLogin'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
